### ISSUE TITLE
Change colors for text and meter

### ISSUE THREAD

**Issue by BladeScraper-Designs** [IRTrail/Horus-Widgets#2]
My radio background is basically white so the white text is super hard if not impossible to see.  And the green bar is pretty odd.  I think having text and meter color options in Widget Settings would be awesome.  Other than that, I like the widget!

**Comment by IRTrail** [comment]
I can either put an option for shadowed text or color option in. Ultimately I would like to figure out how to get the user theme text color as set in the rest of the radio and use that. Keep in mind, OpenTX limits to five options passed to the widget. So keeping color options out allows for further utility options in the future. That's why I would like to figure out how to make it dynamically change text color with the rest of the radio theme.

The gauge turns from green to yellow at 10% then red at 5%. I could change the base color from green to something else. But, I am colorblind so I don't know what would be visible but aesthetically pleasing to people who aren't colorblind.

Also, thanks for the feedback! I really appreciate it!

**Comment by IRTrail** [comment]
I have updated the widget to allow user color selection. Try it.
The gauge is now the same color as the text until 10% when it turns yellow, then red at 5%.
